### ISSUE TITLE
list-course-assignments failure if course name contains comma

### ISSUE THREAD

**Issue by jaimetaplin** [vericite/canvas-utils#1]
If a course in the courses file (downloaded via "canvas-utils/list-courses/list-courses.go") contains a comma, the list-course-assignments process that references that file will fail and throw an error on line 89 of "canvas-utils/list-course-assignments/list-course-assignments.go".  I was able to work around the problem by removing the commas from any course name in the course file.

**Comment by baholladay** [comment]
Thanks, we'll look into this!
